import express from "express";
import Lab5 from "./lab5.js";
import courseroutes from "./courses/routes.js";
import moduleroutes from "./modules/routes.js";
import "dotenv/config";
import cors from "cors";
const app = express();
app.use(cors());
app.use(express.json());
moduleroutes(app);
courseroutes(app);
Lab5(app);
app.listen(process.env.PORT || 4000);